sudo: false

compiler: gcc
language: c
os: linux

services:
  - docker

before_install:
  - docker pull grilofw/grilo:base
  
script:
  - echo FROM grilofw/grilo:base > Dockerfile
  - echo ADD . /root/grilo >> Dockerfile
  - echo WORKDIR /root/grilo >> Dockerfile
  - echo RUN ./autogen.sh \
    --prefix /usr \
    --enable-gtk-doc
    --enable-introspection \
    --enable-vala \
    --enable-test-ui \
    --enable-grl-net \
    --enable-grl-pls >> Dockerfile
  - echo RUN make >> Dockerfile
  - echo RUN make install >> Dockerfile
  - docker build -t grilofw/grilo:core .
  
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && -n "$DOCKER_USERNAME" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push grilofw/grilo:core;
    fi
